<a href="https://colab.research.google.com/github/aaryanML/Pytorch/blob/main/Tensors_in_PyTorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import pytorch

In [ ]:
# check the version of pytorch

In [ ]:
# check if gpu is available or not , print the name of gpu if available else print cpu available


# Creating a Tensor

In [ ]:
# using empty


In [ ]:
# check type


In [ ]:
# using zeros


In [ ]:
# using ones


In [ ]:
# using rand -> random values between 0 and 1


can you see the problem.\
different tensors are generated each time i call tensor.rand(2,3)\
To produce reproducibilty, use **manual_seed**

In [ ]:
# manual_seed


In [ ]:
# using tensor -> generate custom tensor


In [ ]:
# other ways

# using arange


# using linspace


# using eye -> identity matrix


# using full


# Tensor Data Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# finding datatype


In [ ]:
# assign datatype
# assign float64 datatype to tensor



In [ ]:
# using to() -> change datatype of existing tensor


# Tensor Shapes



In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# find shape of tensor


In [ ]:
# empty_like -> same shape as x


In [ ]:
# zeros_like


In [ ]:
# ones_like


In [ ]:
# rand_like


torch.rand_like() creates a tensor with random floating-point values and the same shape and dtype as the input tensor.

Your tensor x has dtype Long (torch.int64), so PyTorch doesn't know how to generate uniform random numbers directly into an integer tensor.

# Mathematical Operations

### 1. Scaler Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition


In [ ]:
# substraction


In [ ]:
# multiplication


In [ ]:
# division


In [ ]:
# int division


In [ ]:
# mod


In [ ]:
# power


### 2. Element-wise Operations

In [ ]:
a = torch.randint(size=(2,3),low = 1,high = 10)
b = torch.randint(size=(2,3),low = 1,high = 10)

print(a)
print(b)

tensor([[3, 7, 7],
        [4, 9, 3]])
tensor([[7, 6, 7],
        [4, 1, 7]])


In [ ]:
# add


In [ ]:
# sub


In [ ]:
# multiply


In [ ]:
# division


In [ ]:
# power


In [ ]:
# mod


_____________________________________________________________

In [ ]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
# abs


In [ ]:
# negative


____________________________________________________________________________________


In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [ ]:
# round


In [ ]:
# ceil


In [ ]:
#floor


In [ ]:
#clamp


### 3. Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 9., 8.],
        [9., 7., 9.]])

In [ ]:
# sum


# sum along columns


# sum along rows


In [ ]:
# mean


# mean along col


In [ ]:
# median


In [ ]:
# max and min


In [ ]:
# product


In [ ]:
# standard deviation


In [ ]:
# variance


In [ ]:
# argmax and argmax


### 4. Matrix Operation

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1],
        [5, 5],
        [0, 4]])


In [ ]:
#matrix multiplication


In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product


tensor(11)

In [ ]:
# transpose


tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [42]:
# determinant


In [43]:
# inverse


### 5. Comparison Operation

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [44]:
# greater than


In [45]:
# less than


In [46]:
# equal to


In [47]:
# not equal to


In [48]:
# greater than equal to


In [49]:
# less than equal to


### 6. Special Functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
k

tensor([[4., 5., 6.],
        [9., 2., 3.]])

In [50]:
# log


In [51]:
# exp


In [52]:
# sqrt


In [53]:
# sigmoid


In [54]:
# softmax
# over columns

In [55]:
# relu


# Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])


In [57]:
# add m and n

In [56]:
# see permanent changes in m

In [60]:
# apply relu on m


# Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b = a

In [61]:
# check memory address of both a and b

both a and b point to the same memory location\
changes in either will be reflected in both\

Solution -> use clone()

In [ ]:
# use clone()

In [62]:
# check memory address of both a and b

# Tensor Operations on GPU

In [64]:
# check if gpu is available

In [ ]:
# assign a name to gpu

In [63]:
# creating a new tensor on GPU


___________________________________________________________________________________________________________________________

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5534, 0.2682, 0.9556],
        [0.9761, 0.5934, 0.3124]])

In [64]:
# moving an existing tensor to GPU

### Performance Comparison between CPU and GPU

In [65]:
# compare the performance of cpu and gpu by matrix multiplication of 2 matrices of size 10000*10000

# Define the size of matrices


# create random matrices on CPU

# measure time on CPU
# matrix multiplication on CPU



# move matrices to GPU


# measure time on GPU
# matrix multiplication on GPU


# Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
# reshape


In [67]:
# flatten


__________________________________________________________________________________________________

In [ ]:
b = torch.rand(2,3)
b

tensor([[0.2635, 0.9755, 0.7084],
        [0.5350, 0.8281, 0.1089]])

In [68]:
# permute -> reordering/relabeling the axes/dimensions of the tensor



In [70]:
# unsqueeze -> Adds a dimension of size 1 at the specified position

# single image to batch containing single image
c = torch.rand(226,226,3)


In [71]:
# squeeze -> Removes dimensions whose size is 1
d = torch.rand(20,1,3)


# Numpy and Pytorch

NumPy and PyTorch are highly compatible. You can easily convert data between them.

In [ ]:
# convert a pytorch tensor to numpy array

In [ ]:
# convert a numpy array to pytorch tensor

A GPU tensor cannot be converted directly to NumPy
because NumPy only works on CPU memory.

In [ ]:
# convert a tensor on gpu to