<a href="https://colab.research.google.com/github/aaryanML/Pytorch/blob/main/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch

In [ ]:
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'Using GPU : {torch.cuda.get_device_name(0)}')
else:
  print('GPU not available. Using CPU')

GPU is available
Using GPU : Tesla T4


# Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[3.2249e-07, 0.0000e+00, 0.0000e+00],
        [1.5046e-36, 2.6963e-11, 0.0000e+00]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand -> random values between 0 and 1
torch.rand(2,3)

tensor([[0.9160, 0.0818, 0.5575],
        [0.6911, 0.8579, 0.0568]])

In [ ]:
torch.rand(2,3)

tensor([[0.6505, 0.5232, 0.1104],
        [0.9057, 0.1657, 0.1891]])

can you see the problem.\
different tensors are generated each time i call tensor.rand(2,3)\
To produce reproducibilty, use **manual_seed**

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor -> generate custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# using arange
print('using arange -> ',torch.arange(0,10,2)) # 2 is the step size here

# using linspace
print('using linspace -> ',torch.linspace(0,10,10))

# using eye -> identity matrix
print('using eye -> ',torch.eye(5))

# using full
print('using full -> ',torch.full((2,3),5))

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5]])


# Tensor Data Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# finding datatype
x.dtype

torch.int64

In [ ]:
# assign datatype

torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to() -> change datatype of existing tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Tensor Shapes



In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# empty_like -> same shape as x
torch.empty_like(x)

tensor([[214748364844, 219043332140, 188978561117],
        [223338299483, 227633266732, 231928234028]])

In [ ]:
# zeros_like
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# ones_like
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# rand_like
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

torch.rand_like() creates a tensor with random floating-point values and the same shape and dtype as the input tensor.

Your tensor x has dtype Long (torch.int64), so PyTorch doesn't know how to generate uniform random numbers directly into an integer tensor.

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Mathematical Operations

### 1. Scaler Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
# substraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
# multiplication
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [ ]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [ ]:
# int division
(x * 100)//3

tensor([[23., 26.],
        [13., 30.]])

In [ ]:
# mod
((x * 100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [ ]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element-wise Operations

In [ ]:
a = torch.randint(size=(2,3),low = 1,high = 10)
b = torch.randint(size=(2,3),low = 1,high = 10)

print(a)
print(b)

tensor([[3, 7, 7],
        [4, 9, 3]])
tensor([[7, 6, 7],
        [4, 1, 7]])


In [ ]:
# add
a + b

tensor([[10, 13, 14],
        [ 8, 10, 10]])

In [ ]:
# sub
a - b

tensor([[-4,  1,  0],
        [ 0,  8, -4]])

In [ ]:
# multiply
a * b

tensor([[21, 42, 49],
        [16,  9, 21]])

In [ ]:
# division
a / b

tensor([[0.4286, 1.1667, 1.0000],
        [1.0000, 9.0000, 0.4286]])

In [ ]:
# power
a ** b

tensor([[  2187, 117649, 823543],
        [   256,      9,   2187]])

In [ ]:
# mod
a % b

tensor([[3, 1, 0],
        [0, 0, 3]])

_____________________________________________________________

In [ ]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
#abs,negative,round,ceil,floor,clamp

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

____________________________________________________________________________________


In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 9., 8.],
        [9., 7., 9.]])

In [ ]:
# sum
print(torch.sum(e))

# sum along columns
print(torch.sum(e, dim=0))

# sum along rows
print(torch.sum(e, dim=1))

tensor(47.)
tensor([14., 16., 17.])
tensor([22., 25.])


In [ ]:
# mean
print(torch.mean(e))

# mean along col
print(torch.mean(e, dim=0))

tensor(7.8333)
tensor([7.0000, 8.0000, 8.5000])


In [ ]:
# median
torch.median(e)

tensor(8.)

In [ ]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(5.)


In [ ]:
# product
torch.prod(e)

tensor(204120.)

In [ ]:
# standard deviation
torch.std(e)

tensor(1.6021)

In [ ]:
# variance
torch.var(e)

tensor(2.5667)

In [ ]:
# argmax and argmax
print(torch.argmax(e))
print(torch.argmin(e))

tensor(1)
tensor(0)


### 4. Matrix Operation

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1],
        [5, 5],
        [0, 4]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[42, 60],
        [82, 59]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1) # swap 0th and 1st dimension

tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [ ]:
torch.det(h)

tensor(-6.)

In [ ]:
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

### 5. Comparison Operation

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [ ]:
# greater than
i > j

tensor([[False,  True, False],
        [ True, False, False]])

In [ ]:
# less than
i < j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [ ]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# greater than equal to
i >= j

tensor([[False,  True, False],
        [ True, False, False]])

In [ ]:
# less than equal to
i <= j

tensor([[ True, False,  True],
        [False,  True,  True]])

### 6. Special Functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
k

tensor([[4., 5., 6.],
        [9., 2., 3.]])

In [ ]:
# log
torch.log(k)

tensor([[1.3863, 1.6094, 1.7918],
        [2.1972, 0.6931, 1.0986]])

In [ ]:
# exp
torch.exp(k)

tensor([[5.4598e+01, 1.4841e+02, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.0086e+01]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 2.2361, 2.4495],
        [3.0000, 1.4142, 1.7321]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9933, 0.9975],
        [0.9999, 0.8808, 0.9526]])

In [ ]:
# softmax
torch.softmax(k, dim=0) # over columns

tensor([[0.0067, 0.9526, 0.9526],
        [0.9933, 0.0474, 0.0474]])

In [ ]:
# relu
torch.relu(k)

tensor([[4., 5., 6.],
        [9., 2., 3.]])

# Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])


In [ ]:
m.add_(n)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [ ]:
m # permanent changes in m

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [ ]:
n

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
m.relu_()

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

# Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b = a

In [ ]:
print(id(a))
print(id(b))

135876080328432
135876080328432


both a and b point to the same memory location\
changes in either will be reflected in both\

Solution -> use clone()

In [ ]:
b = a.clone()

In [ ]:
print(id(a))
print(id(b))

135876080328432
135875740415904


# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.5534, 0.2682, 0.9556],
        [0.9761, 0.5934, 0.3124]])

In [ ]:
b = a.to(device)

In [ ]:
b

tensor([[0.5534, 0.2682, 0.9556],
        [0.9761, 0.5934, 0.3124]], device='cuda:0')

### Performance Comparison between CPU and GPU

In [ ]:
import time

# Define the size of matrices
size = 10000

# create random matrices on CPU
matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2) # matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f'Time on CPU : {cpu_time:.4f} seconds')

# move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2) # matrix multiplication on GPU
torch.cuda.synchronize() # Waits for all pending GPU operations to complete before proceeding
gpu_time = time.time() - start_time

print(f'Time on GPU : {gpu_time:.4f} seconds')

print(f'\nSpeed Up (CPU time / GPU time) : {cpu_time/gpu_time}')

Time on CPU : 16.6696 seconds
Time on GPU : 0.6047 seconds

Speed Up (CPU time / GPU time) : 27.568367012992134


# Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

__________________________________________________________________________________________________

In [ ]:
b = torch.rand(2,3)
b

tensor([[0.2635, 0.9755, 0.7084],
        [0.5350, 0.8281, 0.1089]])

In [ ]:
# permute -> reordering/relabeling the axes/dimensions of the tensor

b.permute(1,0)

tensor([[0.2635, 0.5350],
        [0.9755, 0.8281],
        [0.7084, 0.1089]])

In [ ]:
# unsqueeze -> Adds a dimension of size 1 at the specified position

# single image to batch containing single image
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze -> Removes dimensions whose size is 1
d = torch.rand(20,1,3)
d.squeeze().shape

torch.Size([20, 3])

# Numpy and Pytorch

NumPy and PyTorch are highly compatible. You can easily convert data between them.

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [23]:
b = a.numpy()
b

In [ ]:
type(b)

In [ ]:
c = np.array([1,2,3,4])
c

In [ ]:
d = torch.from_numpy(a)
d

In [ ]:
type(d)

A GPU tensor cannot be converted directly to NumPy\
because NumPy only works on CPU memory.

In [ ]:
t = torch.tensor([1,2,3],device=device)
t

In [ ]:
t.numpy()

In [ ]:
t.cpu().numpy()